### PR TITLE
Add support in arm architechture

### PR DESCRIPTION
**Pull request by yannayl**

### CODE REVIEW

**Comment by yannayl** [comment]
I think it's okay, but lets check it before we merge, okay?
i think it will take about 10 minutes

**Comment by yannayl** [comment]
remember that if you want to install arm, you must have qemu-arm-static in your path and use the -q switch to enable chrooting

**Comment by yannayl** [comment]
check it, all archs are bootstrapping well.
seems ok to me :+1:

**Comment by tokland** [comment]
seems ok to me also, merged. thanks very much!

**Comment by yannayl** [comment]
my pleasure :)

**Pull request merged**
