### PR TITLE
added arm+chroot support +

### PR DESCRIPTION
**Pull request by yannayl**
added cross x86-arm support for bootstrap
using qemu to chroot

### CODE REVIEW

**Comment by yannayl** [comment]
see #11

**Comment by tokland** [comment]
Merged, thx. But:

```
$ bash arch-bootstrap.sh -a arm arch-arm
--- destination directory: arch-arm
--- core repository: http://mirrors.kernel.org/archlinux/core/os/arm
--- temporary directory: /tmp/tmp.YoHQXOV69X
--- fetch packages list: http://mirrors.kernel.org/archlinux/core/os/arm/
--- Error: cannot fetch packages list: http://mirrors.kernel.org/archlinux/core/os/arm
--- pacman package and dependencies: acl archlinux-keyring attr bzip2 curl expat glibc gpgme libarchive libassuan libgpg-error libssh2 lzo openssl pacman pacman-mirrorlist xz zlib krb5 e2fsprogs keyutils libidn gcc-libs filesystem
--- Error: cannot find package: acl
```
 
Any idea?

**Comment by yannayl** [comment]
hmm... no, but i closed this merge and opened another one instead (clean and all).
I think its best if you drop those commits.
if you need help with the git dark-magic, tell me (i went through quite lot of it in the last days)

**Comment by tokland** [comment]
Oh, my, I was in a hurry and I guessed I botched it! By all means, if you want to create a new pull request that fixes the mess, I'll pull it :) (if that's the easiest way)

**Comment by yannayl** [comment]
it's already waiting :)
#11 is based on #10
i just fixed #10 according to the merge of #9 
so... hmmm... i don't know whats the status of the repo now (i got conflicting emails and git-fetch)

**Comment by yannayl** [comment]
i know what the issue is, it's a bad merge :/
please rebase master to 75f1aad304676b0c3832def9c9b99e155b8cb199
and i will fix the pull requests

**Comment by tokland** [comment]
```
arnau@latitude:~/src/arch-bootstrap$ git checkout yannayl-arm
Switched to branch 'yannayl-arm'
arnau@latitude:~/src/arch-bootstrap$ git branch -D master
Deleted branch master (was d9a2a5b).
arnau@latitude:~/src/arch-bootstrap$ git checkout -b master 75f1aad
Switched to a new branch 'master'
arnau@latitude:~/src/arch-bootstrap$ git push --force origin master
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/tokland/arch-bootstrap
 + d9a2a5b...75f1aad master -> master (forced update)
```

**Comment by yannayl** [comment]
cool

**Comment by yannayl** [comment]
now, please merge #10

**Comment by tokland** [comment]
Done. But I still get the acl error.

**Comment by yannayl** [comment]
are you trying to bootstrap the arm architecture or x86_64?

**Comment by tokland** [comment]
The arm. In my x86_64 machine:

```
$ git log | head -n1
commit acc4fe97ebfa4703f8a4c7985f12e5f99ae9ec87
$ bash arch-bootstrap.sh -a arm arch-arm
--- destination directory: arch-arm
--- core repository: http://mirrors.kernel.org/archlinux/core/os/arm
--- temporary directory: /tmp/tmp.Gkr0hO62Jb
--- fetch packages list: http://mirrors.kernel.org/archlinux/core/os/arm/
--- Error: cannot fetch packages list: http://mirrors.kernel.org/archlinux/core/os/arm
--- pacman package and dependencies: acl archlinux-keyring attr bzip2 curl expat glibc gpgme libarchive libassuan libgpg-error libssh2 lzo openssl pacman pacman-mirrorlist xz zlib krb5 e2fsprogs keyutils libidn filesystem
--- Error: cannot find package: acl
```

**Comment by yannayl** [comment]
the arm is not merged yet, remember?
we went back in time and changed history :)

i am working on making a new pull request for it

**Comment by tokland** [comment]
Ok :)

**Comment by yannayl** [comment]
ok, so I opened another pull request for arm, but it will take me about 10 minutes to test it or so

**Pull request closed without merging**
