### PR TITLE
replace pacman --force with --overwrite

### PR DESCRIPTION
**Pull request by shizonic**

### CODE REVIEW

**Comment by dilawar** [comment]
Can this be merged? I ran into similar problem today and this fixed it.

**Comment by jschwartzenberg** [comment]
This PR brings all kinds of formatting changes along in the same commit. That doesn't make the diff very readable. Maybe merge https://github.com/tokland/arch-bootstrap/pull/43 instead?

**Comment by shizonic** [comment]
> This PR brings all kinds of formatting changes along in the same commit. That doesn't make the diff very readable. Maybe merge #43 instead?

It's formatted shfmt's defaul canonical.sh style. So hopefully this isn't the reason to prevent merging it.

**Comment by jschwartzenberg** [comment]
I would suggest either putting the formatting changes in a separate commit and possibly a second PR or leaving them out completely. Now the commit/PR is not very readable.

**Comment by shizonic** [comment]
Agreed. I'll split it into two commits asap. But anyway I think it wouldn't get merged... Seems to be unmaintained for a long time.

**Comment by tokland** [comment]
Thx, https://github.com/tokland/arch-bootstrap/pull/44/files should cover this.

**Pull request closed without merging**
